debug: true
server:
  port: 443
#  servlet:
#    context-path: /ssl-enable-springboot
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: changeme
    key-store-password: changeme

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/sales
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
#FACEBOOK_APP_ID (clientId), FACEBOOK_APP_SECRET(clientSecret)
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 1084065582666070
            clientSecret: 7de71ff1a7f292f58ff9b0ffe874a15c
            scope:
              - email
              - public_profile