---
server:
  port: 8080
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
             - email
             - profile
datasource:
  sampleapp:
    url: jdbc:mysql://127.0.0.1:3306/tmcMum01?usessl=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL55Dialect

---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

